spring:
  application:
    name: spring-cloud-eureka-feign-client

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

endpoints:
  enabled: true
  info:
    enabled: true
info:
  app:
    name: ${spring.application.name}
    encoding: UTF-8
    java:
      source: 1.8
      target: 1.8